local_backend: true
backend:
  name: git-gateway

media_folder: 'src/static/images' # Media files will be stored in the repo under static/images/uploads
public_folder: '/static/images' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'diagram'
    label: 'Diagram'
    create: true # Allow users to create new documents in this collection
    format: json
    slug: '{{fields.name}}'
    preview_path: diagrams/detail/{{slug}}
    folder: 'src/static/diagrams'
    fields:
      - {
          label: 'Group',
          name: 'group',
          widget: 'select',
          required: true,
          options:
            [
              'rate-limiting',
              'buffer',
              'error-handling',
              'combine',
              'merge',
              'scan',
              'condition',
              'timing',
              'transform',
              'filter',
              'side-effect',
              'multicast',
              'scheduling',
              'slice',
              'subject',
              'creation',
            ],
        }
      - {
          label: 'Name',
          name: 'name',
          widget: 'string',
          required: true,
          pattern:
            [
              '^[A-Z]?[a-z]+(?:[A-Z][a-z]+)*$',
              'Name has to be in camelCase or PascalCase',
            ],
        }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
