"use strict";
exports.__esModule = true;
exports.data = [
    {
        "id": 1,
        "name": "audit",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 2,
        "name": "auditTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 3,
        "name": "buffer",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Buffering",
        "oldSchool": "Transformation",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 4,
        "name": "bufferCount",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Buffering",
        "oldSchool": "Transformation",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 5,
        "name": "bufferTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Buffering",
        "oldSchool": "Transformation",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 6,
        "name": "bufferToggle",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Buffering",
        "oldSchool": "Transformation",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 7,
        "name": "bufferWhen",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Buffering",
        "oldSchool": "Transformation",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 8,
        "name": "catchError",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "ErrorHandling",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 9,
        "name": "combineAll",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 10,
        "name": "combineLatest",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 11,
        "name": "concat",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 12,
        "name": "concatAll",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 13,
        "name": "concatMap",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 14,
        "name": "concatMapTo",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 15,
        "name": "count",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Reducing",
        "oldSchool": "None",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 16,
        "name": "debounce",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 17,
        "name": "debounceTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 18,
        "name": "defaultIfEmpty",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Conditional",
        "michael": "Condition",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 19,
        "name": "delay",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Delaying",
        "oldSchool": "Utility",
        "michael": "Timing",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 20,
        "name": "delayWhen",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Delaying",
        "oldSchool": "Utility",
        "michael": "Timing",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 21,
        "name": "dematerialize",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Utility",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 22,
        "name": "distinct",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Filtering",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 23,
        "name": "distinctUntilChanged",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Filtering",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 24,
        "name": "distinctUntilKeyChanged",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Filtering",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 25,
        "name": "elementAt",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Finding",
        "oldSchool": "None",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 26,
        "name": "endWith",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 27,
        "name": "every",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Conditional",
        "oldSchool": "Conditional",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 28,
        "name": "exhaust",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Converting",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 29,
        "name": "exhaustMap",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 30,
        "name": "expand",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 31,
        "name": "filter",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 32,
        "name": "finalize",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Utility",
        "michael": "Side-Effect",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 33,
        "name": "find",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Finding",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 34,
        "name": "findIndex",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Finding",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 35,
        "name": "first",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 36,
        "name": "groupBy",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 37,
        "name": "ignoreElements",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 38,
        "name": "isEmpty",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Conditional",
        "oldSchool": "None",
        "michael": "Condition",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 39,
        "name": "last",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 40,
        "name": "map",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Mapping",
        "oldSchool": "Transformation",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 41,
        "name": "mapTo",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Mapping",
        "oldSchool": "Transformation",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 42,
        "name": "materialize",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 43,
        "name": "max",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Reducing",
        "oldSchool": "None",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 44,
        "name": "merge",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 45,
        "name": "mergeAll",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Converting",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 46,
        "name": "mergeMap",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 47,
        "name": "flatMap",
        "isDeprecate": "No",
        "isAlias": "Yes",
        "cedric": "Flattening",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 48,
        "name": "mergeMapTo",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Transformation",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 49,
        "name": "mergeScan",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Scanning",
        "oldSchool": "None",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 50,
        "name": "min",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Reducing",
        "oldSchool": "None",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 51,
        "name": "multicast",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "Multicasting",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 52,
        "name": "observeOn",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Scheduling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 53,
        "name": "onErrorResumeNext",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 54,
        "name": "pairwise",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Scanning",
        "oldSchool": "Combination",
        "michael": "Buffer",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 55,
        "name": "partition",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Filtering",
        "oldSchool": "Transformation",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 56,
        "name": "pluck",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Mapping",
        "oldSchool": "Transformation",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 57,
        "name": "publish",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "Multicasting",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 58,
        "name": "publishBehavior",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "None",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 59,
        "name": "publishLast",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "None",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 60,
        "name": "publishReplay",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "None",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 61,
        "name": "race",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Condition",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 62,
        "name": "reduce",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Reducing",
        "oldSchool": "Mathematical and Aggregate",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 63,
        "name": "repeat",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Utility",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 64,
        "name": "repeatWhen",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 65,
        "name": "retry",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "ErrorHandling",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 66,
        "name": "retryWhen",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "ErrorHandling",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 67,
        "name": "refCount",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "None",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 68,
        "name": "sample",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "None",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 69,
        "name": "sampleTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 70,
        "name": "scan",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Scanning",
        "oldSchool": "Transformation",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 71,
        "name": "sequenceEqual",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Conditional",
        "oldSchool": "Conditional",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 72,
        "name": "share",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "Multicasting",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 73,
        "name": "shareReplay",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Sharing",
        "oldSchool": "Multicasting",
        "michael": "Multicast",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 74,
        "name": "single",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Flattening",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 75,
        "name": "skip",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 76,
        "name": "skipLast",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 77,
        "name": "skipUntil",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 78,
        "name": "skipWhile",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 79,
        "name": "startWith",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 80,
        "name": "subscribeOn",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Scheduling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 81,
        "name": "switchAll",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 82,
        "name": "switchMap",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 83,
        "name": "switchMapTo",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Merge",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 84,
        "name": "switchScan",
        "isDeprecate": "",
        "isAlias": "",
        "cedric": "",
        "oldSchool": "",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 85,
        "name": "take",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 86,
        "name": "takeLast",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 87,
        "name": "takeUntil",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 88,
        "name": "takeWhile",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Slicing",
        "oldSchool": "Filter",
        "michael": "Filter",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 89,
        "name": "tap",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Utility",
        "michael": "Side-Effect",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 90,
        "name": "throttle",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 91,
        "name": "throttleTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Rate-limiting",
        "oldSchool": "Filter",
        "michael": "Rate-Limit",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 92,
        "name": "throwIfEmpty",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "ErrorHandling",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 93,
        "name": "timeInterval",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 94,
        "name": "timeout",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "Utility",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 95,
        "name": "timeoutWith",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Error-Handling",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 96,
        "name": "timestamp",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Misc",
        "oldSchool": "None",
        "michael": "Transform",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 97,
        "name": "toArray",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Reducing",
        "oldSchool": "Transformation",
        "michael": "Scan",
        "isOperator": "operator",
        "hoo": "FirstOrder"
    },
    {
        "id": 98,
        "name": "window",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Windowing",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 99,
        "name": "windowCount",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Windowing",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 100,
        "name": "windowTime",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Windowing",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 101,
        "name": "windowToggle",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Windowing",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 102,
        "name": "windowWhen",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Windowing",
        "oldSchool": "Transformation",
        "michael": "Slice",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 103,
        "name": "withLatestFrom",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 104,
        "name": "zip",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 105,
        "name": "zipAll",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Converting",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "operator",
        "hoo": "HigherOrder"
    },
    {
        "id": 106,
        "name": "AsyncSubject",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Subject",
        "michael": "Subject",
        "isOperator": "static",
        "hoo": "None"
    },
    {
        "id": 107,
        "name": "BehaviorSubject",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Subject",
        "michael": "Subject",
        "isOperator": "static",
        "hoo": "None"
    },
    {
        "id": 108,
        "name": "combineLatest",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "None",
        "michael": "Combine",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 109,
        "name": "concat",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 110,
        "name": "create (Observable.create)",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 111,
        "name": "defer",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 112,
        "name": "EMPTY",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 113,
        "name": "forkJoin",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 114,
        "name": "from",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 115,
        "name": "fromEvent",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 116,
        "name": "fromEventPattern",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 117,
        "name": "generate",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 118,
        "name": "iif",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Conditional",
        "michael": "Condition",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 119,
        "name": "interval",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Timing",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 120,
        "name": "merge",
        "isDeprecate": "Yes",
        "isAlias": "No",
        "cedric": "Merging",
        "oldSchool": "Combination",
        "michael": "Merge",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 121,
        "name": "NEVER",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 122,
        "name": "of",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 123,
        "name": "onErrorResumeNext",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Error-Handling",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 124,
        "name": "pairs",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Transform",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 125,
        "name": "race",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Condition",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 126,
        "name": "range",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Creation",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 127,
        "name": "ReplaySubject",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Subject",
        "michael": "Subject",
        "isOperator": "static",
        "hoo": "None"
    },
    {
        "id": 128,
        "name": "Subject",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Subject",
        "michael": "Subject",
        "isOperator": "static",
        "hoo": "None"
    },
    {
        "id": 129,
        "name": "throwError",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Error-Handling",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 130,
        "name": "timer",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "Creation",
        "michael": "Timing",
        "isOperator": "static",
        "hoo": "FirstOrder"
    },
    {
        "id": 131,
        "name": "zip",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "Combining",
        "oldSchool": "Combination",
        "michael": "Combine",
        "isOperator": "static",
        "hoo": "HigherOrder"
    },
    {
        "id": 132,
        "name": "scheduled",
        "isDeprecate": "No",
        "isAlias": "No",
        "cedric": "None",
        "oldSchool": "None",
        "michael": "Scheduling",
        "isOperator": "static",
        "hoo": "FirstOrder"
    }
];
