name: CI

on:
  push:
    branches:
      - main

env:
  BASE: origin/main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Audit production dependencies
        run: npm audit --only=prod --audit-level=high

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Check formatting
        run: npm run prettier:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linters
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run production builds
        run: npm run build
